version: '3'

services:

  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  microsservico-a:
    image: schmidtech/microsservico-avancadev-a
    ports:
      - 9090:9090
  microsservico-b:
    image: schmidtech/microsservico-avancadev-b
  microsservico-c:
    image: schmidtech/microsservico-avancadev-c
    ports:
      - 9092:9092

